### 19CSE305: Machine Learning

Name: Laxman K R

Roll: CB.EN.U4CSE20234

**Binary Classification using Perceptron**

In [1]:
## Import required libraries

import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn

from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split

In [2]:
diabdata = pd.read_csv("glass.csv")
print(diabdata.shape)
diabdata.describe().transpose()

(214, 10)


count       mean       std       min        25%       50%        75%  \
RI    214.0   1.518365  0.003037   1.51115   1.516522   1.51768   1.519157   
Na    214.0  13.407850  0.816604  10.73000  12.907500  13.30000  13.825000   
Mg    214.0   2.684533  1.442408   0.00000   2.115000   3.48000   3.600000   
Al    214.0   1.444907  0.499270   0.29000   1.190000   1.36000   1.630000   
Si    214.0  72.650935  0.774546  69.81000  72.280000  72.79000  73.087500   
K     214.0   0.497056  0.652192   0.00000   0.122500   0.55500   0.610000   
Ca    214.0   8.956963  1.423153   5.43000   8.240000   8.60000   9.172500   
Ba    214.0   0.175047  0.497219   0.00000   0.000000   0.00000   0.000000   
Fe    214.0   0.057009  0.097439   0.00000   0.000000   0.00000   0.100000   
Type  214.0   2.780374  2.103739   1.00000   1.000000   2.00000   3.000000   

           max  
RI     1.53393  
Na    17.38000  
Mg     4.49000  
Al     3.50000  
Si    75.41000  
K      6.21000  
Ca    16.19000  
Ba     3.15000  
Fe     0.51000  
Type   7.00000

In [3]:
## Create Arrays for features and response variables

target_column = ['Type'] 
predictors = list(set(list(diabdata.columns))-set(target_column))
diabdata[predictors] = diabdata[predictors]/diabdata[predictors].max()
diabdata.describe().transpose()

count      mean       std       min       25%       50%       75%  max
RI    214.0  0.989853  0.001980  0.985149  0.988652  0.989406  0.990370  1.0
Na    214.0  0.771453  0.046985  0.617376  0.742664  0.765247  0.795455  1.0
Mg    214.0  0.597891  0.321249  0.000000  0.471047  0.775056  0.801782  1.0
Al    214.0  0.412830  0.142648  0.082857  0.340000  0.388571  0.465714  1.0
Si    214.0  0.963412  0.010271  0.925739  0.958494  0.965257  0.969202  1.0
K     214.0  0.080041  0.105023  0.000000  0.019726  0.089372  0.098229  1.0
Ca    214.0  0.553240  0.087903  0.335392  0.508956  0.531192  0.566553  1.0
Ba    214.0  0.055570  0.157847  0.000000  0.000000  0.000000  0.000000  1.0
Fe    214.0  0.111783  0.191056  0.000000  0.000000  0.000000  0.196078  1.0
Type  214.0  2.780374  2.103739  1.000000  1.000000  2.000000  3.000000  7.0

In [4]:
## Creating Training and Test Datasets

X = diabdata[predictors].values
y = diabdata[target_column].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=40)
print(X_train.shape); print(X_test.shape)

(149, 9)
(65, 9)


In [5]:
## Building NN Model

from sklearn.neural_network import MLPClassifier

## activation : {‘identity’, ‘logistic’, ‘tanh’, ‘relu’}, default=’relu’
## solver : {‘lbfgs’, ‘sgd’, ‘adam’}, default=’adam’

mlp = MLPClassifier(hidden_layer_sizes=(8,8,8), activation='relu', solver='adam', max_iter=500) # Variations w.r.to parameters can be tried.
mlp.fit(X_train,y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

c:\Users\Laxman\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\Laxman\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:702: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


In [6]:
# Model with Training Data
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

[[42  9  0  0  0  0]
 [17 33  0  0  0  1]
 [ 6  3  0  0  0  0]
 [ 0  6  0  0  0  4]
 [ 0  5  0  0  0  1]
 [ 1  0  0  0  0 21]]
              precision    recall  f1-score   support

           1       0.64      0.82      0.72        51
           2       0.59      0.65      0.62        51
           3       0.00      0.00      0.00         9
           5       0.00      0.00      0.00        10
           6       0.00      0.00      0.00         6
           7       0.78      0.95      0.86        22

    accuracy                           0.64       149
   macro avg       0.33      0.40      0.37       149
weighted avg       0.53      0.64      0.58       149



c:\Users\Laxman\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Laxman\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Laxman\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(avera

In [7]:
# Model's Performance with test data
print(confusion_matrix(y_test,predict_test))
print(classification_report(y_test,predict_test))

[[16  3  0  0  0  0]
 [10 15  0  0  0  0]
 [ 7  1  0  0  0  0]
 [ 0  2  0  0  0  1]
 [ 0  3  0  0  0  0]
 [ 0  1  0  0  0  6]]
              precision    recall  f1-score   support

           1       0.48      0.84      0.62        19
           2       0.60      0.60      0.60        25
           3       0.00      0.00      0.00         8
           5       0.00      0.00      0.00         3
           6       0.00      0.00      0.00         3
           7       0.86      0.86      0.86         7

    accuracy                           0.57        65
   macro avg       0.32      0.38      0.35        65
weighted avg       0.46      0.57      0.50        65



c:\Users\Laxman\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Laxman\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Laxman\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(avera